---
title: "Upload files to Drive"
author: "Camila Vargas"
date: "9/30/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(googledrive)
library(tidyverse)

```


## Upload to dive
Data
```{r}

## Finalized data folder url
final_files_url <- "https://drive.google.com/drive/u/0/folders/1XyAzK06QsF9F_JS1T0fnXMr2-VjXjmH-"

## Upload data 
# **UPADATE FILE PATH AND NAME**

drive_upload(media = paste0(getwd(),"/clean_data/2005_palmyra_atoll_crab_home_range_locations.csv"),
             path = as_id(final_files_url),
             name = "2005_palmyra_atoll_crab_home_range_locations.csv",
             type = "csv")



```

Metadata Doc

```{r}
## Upload metadata
# **UPDATE FILE NAME** last_name_topic_metadata

drive_upload(media = here::here("metadata_doc/metadata_doc.docx"),
             path = as_id(final_files_url),
             name = "wegmann_crab_home_loc_metadata.docx",
             type = "docx")
```

xml file

```{r}
# **UPDATE project ID and EDI ID**

drive_upload(media = here::here("project.XX/edi.XX.xml"),
             path = as_id(final_files_url),
             name = "edi.XX.xml")

```

